name: hello_world
run-name: ${{ github.actor }} running hello world
on: [push]
jobs:
  build-n-test:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9
    steps:
      - uses: actions/checkout@v6
      - run: dnf -y install cmake
      - run: sh build.sh
      - run: sh test.sh

