name: system specs
run-name: ${{ github.actor }} probe system specs
on: [push]
jobs:
  lscpu-lsmem:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:10
    steps:
      - run: lscpu
      - run: lsmem

